Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  #config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant
    docker-compose up
  SHELL
end
